import { StyleSheet } from 'react-native';

import { AppTheme } from './app-theme';

const c = AppTheme.colors;
const r = AppTheme.radius;

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: c.background },
  content: { flex: 1, paddingTop: 10 },
  loadingWrap: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  headerWrap: { marginBottom: 10 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 12 },
  title: { fontSize: 26, fontWeight: '800', color: c.text },
  list: { flex: 1 },
  listContent: { paddingBottom: 114 },

  inputRow: { flexDirection: 'row', marginBottom: 10, alignItems: 'center' },
  input: {
    flex: 1,
    backgroundColor: c.surface,
    color: c.text,
    paddingHorizontal: 14,
    paddingVertical: 13,
    borderRadius: r.md,
    borderWidth: 1,
    borderColor: c.border,
  },
  addButton: {
    backgroundColor: c.primary,
    minWidth: 96,
    borderRadius: r.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    paddingVertical: 11,
    paddingHorizontal: 12,
    flexDirection: 'row',
    gap: 4,
  },
  addButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '700' },

  detailRow: { flexDirection: 'row', gap: 8, alignItems: 'center', marginBottom: 10 },
  dateInputWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: r.md,
    paddingHorizontal: 10,
  },
  dateInput: { flex: 1, color: c.text, paddingVertical: 11, fontSize: 13 },
  priorityRow: { flexDirection: 'row', gap: 6 },
  priorityChip: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: r.sm,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  priorityLow: { backgroundColor: c.successSoft },
  priorityMid: { backgroundColor: c.warningSoft },
  priorityHi: { backgroundColor: c.dangerSoft },
  priorityChipActive: { borderColor: c.text },
  priorityChipText: { fontSize: 12, fontWeight: '700', color: c.text },

  cancelEditButton: { marginBottom: 10, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5 },
  cancelEditButtonText: { color: c.danger, fontSize: 13, fontWeight: '600' },

  searchWrap: {
    backgroundColor: c.surface,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: r.md,
    paddingHorizontal: 12,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  searchInput: { flex: 1, color: c.text, paddingVertical: 11, fontSize: 14 },

  filterRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: r.pill,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.surface,
  },
  filterChipActive: { backgroundColor: c.primary, borderColor: c.primary },
  filterChipText: { color: c.textMuted, fontSize: 13, fontWeight: '600' },
  filterChipTextActive: { color: '#FFFFFF' },

  statsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 10 },
  statCard: {
    backgroundColor: c.surfaceAlt,
    borderWidth: 1,
    borderColor: c.border,
    borderRadius: r.md,
    minWidth: 92,
    paddingVertical: 10,
    paddingHorizontal: 10,
  },
  statValue: { color: c.text, fontSize: 16, fontWeight: '800' },
  statLabel: { color: c.textSoft, fontSize: 11, marginTop: 2, fontWeight: '600' },

  statusRow: { marginBottom: 8 },
  statusPills: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 10, paddingVertical: 7, borderRadius: r.pill },
  statusPillOnline: { backgroundColor: c.successSoft },
  statusPillOffline: { backgroundColor: c.dangerSoft },
  statusPillWarning: { backgroundColor: c.warningSoft },
  statusPillText: { fontSize: 11, fontWeight: '700' },
  statusPillTextOnline: { color: '#065F46' },
  statusPillTextOffline: { color: c.danger },
  statusPillTextWarning: { color: '#9A3412' },
  syncButton: {
    backgroundColor: c.accent,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: r.md,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  syncButtonText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  hint: { color: c.textSoft, marginBottom: 12, fontSize: 12 },

  taskRow: { flexDirection: 'row', alignItems: 'stretch', gap: 8, marginBottom: 10 },
  taskCard: {
    flex: 1,
    backgroundColor: c.surface,
    padding: 12,
    borderRadius: r.md,
    borderWidth: 1,
    borderColor: c.border,
  },
  taskHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  taskText: { flex: 1, fontSize: 16, color: c.text, fontWeight: '600' },
  completedText: { textDecorationLine: 'line-through', color: c.textSoft },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  priorityPill: {
    backgroundColor: '#475569',
    borderRadius: r.pill,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  priorityHigh: { backgroundColor: c.danger },
  priorityMedium: { backgroundColor: c.warning },
  priorityPillText: { color: '#FFFFFF', fontSize: 11, fontWeight: '700' },
  duePill: {
    backgroundColor: '#F1F5F9',
    borderRadius: r.pill,
    paddingHorizontal: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  duePillOverdue: { backgroundColor: c.danger },
  deadlineText: { fontSize: 11, color: c.textMuted, fontWeight: '600' },
  deadlineOverdue: { color: '#FFFFFF' },

  actionColumn: { justifyContent: 'space-between', gap: 8 },
  iconActionBtn: {
    width: 42,
    height: 42,
    borderRadius: r.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editBtn: { backgroundColor: c.accent },
  deleteBtn: { backgroundColor: c.danger },

  emptyWrap: { paddingTop: 36, paddingBottom: 24, alignItems: 'center', gap: 8 },
  emptyText: { textAlign: 'center', color: c.textSoft },

  clearButton: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 16,
    backgroundColor: c.primaryDark,
    paddingVertical: 13,
    borderRadius: r.md,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
    shadowColor: c.shadow,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  clearButtonText: { color: '#FFFFFF', fontWeight: '700' },

  undoBar: {
    position: 'absolute',
    left: 18,
    right: 18,
    bottom: 72,
    borderRadius: r.md,
    backgroundColor: c.text,
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  undoText: { color: '#FFFFFF', flex: 1 },
  undoBtn: { backgroundColor: c.success, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  undoBtnText: { color: '#052E16', fontWeight: '800' },
});
